Estilos CSS de paÍses
araceli4920/requisitos-segundo-parcial pull request #31
Opened 2024-07-03 21:54 UTC by Luzclarita18

Se agrego estilos al CSS  eso causo que tuviera que agregar un Link en "paises.html" y JS  se agrego clases para así tener un mejor manejo de las Cards, de la misma maneja se agrego un "img.paises" para ponerle estilo al fondo pero solo es una idea mas no esta implementada en el proyecto del equipo.

2024-07-03 23:14 UTC, mariomatos0 submitted a review, later dismissed
Se reviso lo agregado y todo está correcto se cumple con lo solicitado en el issues

2024-07-04 00:04 UTC, Scar269 commented on paises.css
> +    /*background-image: url("/img.paises/bandera2.jpg");  /*Esto puede cambiarse solo es un fondo para mejor visualización de las card*/
favor de quitar el primer signo de: /*
pues esto impide la visualización del fondo

2024-07-04 00:09 UTC, Scar269 requested changes

2024-07-04 00:09 UTC, Scar269 commented on paises.css
> +    /*background-image: url("/img.paises/bandera2.jpg");  /*Esto puede cambiarse solo es un fondo para mejor visualización de las card*/
favor de quitar el primer signo de: /*
pues esto impide la visualización del fondo

2024-07-04 00:09 UTC, Scar269 commented on paises.js
>              `;
favor de acomodar los divs

2024-07-06 04:35 UTC, Luzclarita18 commented on paises.css
> +    /*background-image: url("/img.paises/bandera2.jpg");  /*Esto puede cambiarse solo es un fondo para mejor visualización de las card*/
perfecto en todos lo arreglo ..gracias

2024-07-07 17:43 UTC, mariomatos0 reviewed
Se reviso lo agregado y se corrigieron los errores

2024-07-07 18:28 UTC, Scar269 approved these changes
Se revisaron los cambios, los errores anteriores han sido corregidos, gracias.

2024-07-07 18:31 UTC, mariomatos0 approved these changes
Se reviso lo agregado y se corrigieron los errores

2024-07-07 18:39 UTC, merged