Implementación del Header de country
araceli4920/requisitos-segundo-parcial pull request #47
Opened 2024-07-12 01:33 UTC by mariomatos0

Se agrega el html  el header que se usara para redirigirse a mas paginas

2024-07-12 02:05 UTC, Scar269 requested changes
favor de agregar el script del hader y sus estilos, tambien agregar el link de la pagina home

2024-07-12 02:23 UTC, mariomatos0 commented
hice la modificación que se me sugiero en el comentario , esperando que puedan checarlo para que se implemente en la main.

2024-07-12 23:00 UTC, Scar269 approved these changes
Todo está correcto, la funcionalidad del botón para el modo obscuro deberá ser agregada en el proximo pull request asignado a Luz Clarita junto a los demás estilos

2024-07-13 00:47 UTC, darkukore approved these changes

2024-07-13 00:47 UTC, darkukore commented on paises.css
> +}
No se dejo la ultima linea de codigo en blanco, favor de agregarla en un pull posterior, en cuanto a lo demas, parece estar en orden.

2024-07-13 00:55 UTC, merged